### PR TITLE
chore(ci): release main

### PR DESCRIPTION
**Pull request by pregno**
:robot: I have created a release *beep* *boop*
---

<details><summary>prettier-config: 1.0.1</summary>

### Bug Fixes

* improve link doc with tabs ([#252](https://github.com/ogcio/govie-ds/issues/252)) ([6925f88](https://github.com/ogcio/govie-ds/commit/6925f88ee92b7fbc717731cb550a7fe5efa636c4))
</details>

<details><summary>tailwind: 0.10.1</summary>

### Bug Fixes

* improve link doc with tabs ([#252](https://github.com/ogcio/govie-ds/issues/252)) ([6925f88](https://github.com/ogcio/govie-ds/commit/6925f88ee92b7fbc717731cb550a7fe5efa636c4))
</details>

<details><summary>html: 0.10.0</summary>

### Features

* add html file-upload component ([#254](https://github.com/ogcio/govie-ds/issues/254)) ([dcce995](https://github.com/ogcio/govie-ds/commit/dcce99568c9ff53f70dbc663fbcac55bdbfe9ead))

### Bug Fixes

* improve link doc with tabs ([#252](https://github.com/ogcio/govie-ds/issues/252)) ([6925f88](https://github.com/ogcio/govie-ds/commit/6925f88ee92b7fbc717731cb550a7fe5efa636c4))
* send formdata on submit and add search url prop ([#251](https://github.com/ogcio/govie-ds/issues/251)) ([0f49978](https://github.com/ogcio/govie-ds/commit/0f499783e4d6a4a5873c3485656a7a67d1280e8a))
</details>

<details><summary>react: 0.14.0</summary>

### Features

* add file upload component ([#247](https://github.com/ogcio/govie-ds/issues/247)) ([8f73a13](https://github.com/ogcio/govie-ds/commit/8f73a1334703324315a63d4a6069d5de1dddcba1))
* add html file-upload component ([#254](https://github.com/ogcio/govie-ds/issues/254)) ([dcce995](https://github.com/ogcio/govie-ds/commit/dcce99568c9ff53f70dbc663fbcac55bdbfe9ead))

### Bug Fixes

* improve link doc with tabs ([#252](https://github.com/ogcio/govie-ds/issues/252)) ([6925f88](https://github.com/ogcio/govie-ds/commit/6925f88ee92b7fbc717731cb550a7fe5efa636c4))
* send formdata on submit and add search url prop ([#251](https://github.com/ogcio/govie-ds/issues/251)) ([0f49978](https://github.com/ogcio/govie-ds/commit/0f499783e4d6a4a5873c3485656a7a67d1280e8a))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by BogdanDanilescu — APPROVED** [review]

**Comment by pregno** [comment]
:robot: Release is at https://github.com/ogcio/govie-ds/releases/tag/prettier-config-v1.0.1 :sunflower:

**Comment by pregno** [comment]
:robot: Release is at https://github.com/ogcio/govie-ds/releases/tag/tailwind-v0.10.1 :sunflower:

**Comment by pregno** [comment]
:robot: Release is at https://github.com/ogcio/govie-ds/releases/tag/html-v0.10.0 :sunflower:

**Comment by pregno** [comment]
:robot: Release is at https://github.com/ogcio/govie-ds/releases/tag/react-v0.14.0 :sunflower:

**Pull request merged**
